-- ============================================================================
-- AB Gestión — esquema completo y modelo de seguridad (documento de referencia)
-- Fecha: 2026-09-13
--
-- QUÉ ES: la definición completa de las 8 tablas, las funciones de permisos,
-- los disparadores (triggers), las políticas de RLS (Row Level Security) y
-- los permisos de rol de este proyecto, tal como están hoy. Se armó
-- extrayendo la definición real de cada objeto con pg_get_functiondef() /
-- pg_get_constraintdef() y las policies de pg_policy, no de memoria: es
-- exactamente lo que hay, no una aproximación.
--
-- PARA QUÉ SIRVE: la aplicación en sí (el código en `js/`) no puede mostrar
-- esto -- corre en el navegador de cada usuario, y la barrera real de
-- permisos vive en la base de datos, no en la pantalla. Este archivo es la
-- forma de verificar esa afirmación sin necesitar acceso directo a la base:
-- cada tabla tiene RLS activa, cada política está escrita acá tal cual existe,
-- y las funciones que corren con privilegios elevados (`security definer`)
-- fijan `search_path` para no quedar expuestas al ataque clásico de ese
-- patrón en Postgres.
--
-- Los datos de ejemplo del PASO 6 son registros fabricados para pruebas: ningún
-- nombre, teléfono, mail o fecha de nacimiento corresponde a una persona real.
--
-- No pensado para correrse de nuevo tal cual contra una base que ya tiene
-- estas tablas -- los "create table" fallarían porque ya existen. Es
-- documentación, no un script de instalación.
-- ============================================================================


-- ============================================================================
-- PASO 1 -- Tablas
-- ============================================================================

create table public.usuarios (
  id uuid primary key default gen_random_uuid(),
  nombre_completo text not null,
  rol text,
  dupla_asignada text[]
);

create table public.catalogos (
  id bigint generated by default as identity primary key,
  tipo text not null,
  valor text,
  activo boolean,
  unique (tipo, valor)
);

create table public.productores (
  id bigint generated by default as identity primary key,
  pas_nombre text not null,
  organizacion text,
  vinculante text,
  ejecutivo text,
  telefono text,
  mail text,
  fecha_nacimiento date,
  companias_opera text,
  cantidad_polizas_vigentes integer,
  observaciones text,
  estado text,
  zona text,
  localidad_prov text,
  version integer not null default 1
);

create table public.producciones (
  id bigint generated by default as identity primary key,
  pas_id bigint not null references public.productores(id),
  ramo text,
  trimestre text,
  ejecutivo text,
  organizador text,
  total_polizas integer,
  ultima_fecha date,
  version integer not null default 1
);

-- Sin FK explícita hacia producciones: se vincula por convención vía
-- produccion_id, controlado enteramente por los RPC (nunca por el frontend
-- directo -- ver crear_produccion_completa/guardar_produccion_completa).
create table public.produccion_companias (
  id bigint generated by default as identity primary key,
  produccion_id bigint not null,
  compania text,
  cantidad integer
);

create table public.metas (
  id bigint generated by default as identity primary key,
  dupla text not null,
  trimestre text not null,
  objetivo_polizas numeric not null check (objetivo_polizas >= 0),
  creado_por uuid references public.usuarios(id),
  creado_en timestamptz not null default now(),
  unique (dupla, trimestre)
);

create table public.reportes (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null default gen_random_uuid(),
  usuario_nombre text,
  vista text,
  mensaje text,
  estado text,
  creado_en timestamptz,
  respuesta text
);

-- registro_id es text (no bigint) a propósito: usuarios.id es uuid, y una
-- columna numérica no puede guardar un uuid. No se usa para hacer joins, solo
-- para mostrarlo en pantalla, así que el tipo de dato de origen no importa.
create table public.audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  usuario_id uuid references public.usuarios(id),
  usuario_nombre text,
  accion text not null,
  tabla text not null,
  registro_id text,
  datos_anteriores jsonb,
  datos_nuevos jsonb
);


-- ============================================================================
-- PASO 2 -- Funciones (helpers de permisos, triggers, y RPC de la app)
-- ============================================================================

create or replace function public.mi_rol()
 returns text
 language sql
 stable security definer
 set search_path to 'public'
as $function$
  select coalesce((select rol from public.usuarios where id = auth.uid()), '')
$function$;

create or replace function public.mi_dupla()
 returns text
 language sql
 stable security definer
 set search_path to 'public'
as $function$ select dupla_asignada from public.usuarios where id = auth.uid() $function$;

create or replace function public.tiene_dupla(p_ejecutivo text)
 returns boolean
 language sql
 stable
 set search_path to 'public'
as $function$
  select p_ejecutivo = any(coalesce((select dupla_asignada from usuarios where id = auth.uid()), '{}'::text[]))
$function$;

create or replace function public.es_admin()
 returns boolean
 language sql
 stable security definer
 set search_path to 'public'
as $function$
  select exists (select 1 from usuarios where id = auth.uid() and rol = 'admin');
$function$;

create or replace function public.es_jefe()
 returns boolean
 language sql
 stable security definer
 set search_path to 'public'
as $function$
  select exists (select 1 from usuarios where id = auth.uid() and rol = 'jefe');
$function$;

-- Genérica: cubre las 7 tablas auditadas (todas menos audit_log en sí y
-- catalogos... ver PASO 4 para cuáles la usan). registro_id se castea a
-- ::text para no depender del tipo de la PK de cada tabla (bigint en la
-- mayoría, uuid en usuarios).
create or replace function public.fn_audit_log()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_usuario_id uuid := auth.uid();
  v_usuario_nombre text;
begin
  select nombre_completo into v_usuario_nombre from public.usuarios where id = v_usuario_id;
  if (tg_op = 'DELETE') then
    insert into public.audit_log (usuario_id, usuario_nombre, accion, tabla, registro_id, datos_anteriores)
    values (v_usuario_id, v_usuario_nombre, 'delete', tg_table_name, old.id::text, to_jsonb(old));
    return old;
  elsif (tg_op = 'UPDATE') then
    insert into public.audit_log (usuario_id, usuario_nombre, accion, tabla, registro_id, datos_anteriores, datos_nuevos)
    values (v_usuario_id, v_usuario_nombre, 'update', tg_table_name, new.id::text, to_jsonb(old), to_jsonb(new));
    return new;
  elsif (tg_op = 'INSERT') then
    insert into public.audit_log (usuario_id, usuario_nombre, accion, tabla, registro_id, datos_nuevos)
    values (v_usuario_id, v_usuario_nombre, 'insert', tg_table_name, new.id::text, to_jsonb(new));
    return new;
  end if;
  return null;
end;
$function$;

create or replace function public.fn_bump_version()
 returns trigger
 language plpgsql
 set search_path to 'public'
as $function$
begin
  new.version := coalesce(old.version, 0) + 1;
  return new;
end;
$function$;

create or replace function public.fn_recalcular_total_produccion()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_produccion_id bigint;
  v_total numeric;
begin
  v_produccion_id := coalesce(new.produccion_id, old.produccion_id);
  select coalesce(sum(cantidad),0) into v_total from public.produccion_companias where produccion_id = v_produccion_id;
  update public.producciones set total_polizas = v_total where id = v_produccion_id;
  return coalesce(new, old);
end;
$function$;

-- BEFORE INSERT/UPDATE: completa el autor desde la sesión (auth.uid()),
-- ignorando lo que mande el navegador. Antes de esto, usuario_nombre lo
-- mandaba el frontend como texto libre y era suplantable.
create or replace function public.fn_reportes_autor()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'pg_catalog'
as $function$
begin
  if tg_op = 'INSERT' then
    new.usuario_id := auth.uid();
    select u.nombre_completo into new.usuario_nombre
      from public.usuarios u
     where u.id = auth.uid();
    if new.usuario_nombre is null then
      new.usuario_nombre := 'Usuario';
    end if;
  elsif tg_op = 'UPDATE' then
    new.usuario_id := old.usuario_id;
    new.usuario_nombre := old.usuario_nombre;
  end if;
  return new;
end;
$function$;

-- Event trigger: activa RLS automáticamente en cualquier tabla nueva del
-- esquema public, como red de seguridad ante el olvido.
create or replace function public.rls_auto_enable()
 returns event_trigger
 language plpgsql
 security definer
 set search_path to 'pg_catalog'
as $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

create or replace function public.crear_produccion_completa(p_pas_id bigint, p_ramo text, p_trimestre text, p_ejecutivo text, p_organizador text, p_fecha date, p_total integer, p_detalle jsonb)
 returns bigint
 language plpgsql
 set search_path to 'public'
as $function$
declare
  v_id bigint;
begin
  insert into public.producciones
    (pas_id, ramo, trimestre, ejecutivo, organizador, ultima_fecha, total_polizas)
  values
    (p_pas_id, p_ramo, p_trimestre, p_ejecutivo, p_organizador, p_fecha, p_total)
  returning id into v_id;

  insert into public.produccion_companias (produccion_id, compania, cantidad)
  select v_id, d->>'compania', (d->>'cantidad')::int
    from jsonb_array_elements(p_detalle) as d;

  return v_id;
end;
$function$;

create or replace function public.guardar_produccion_completa(p_produccion_id bigint, p_ramo text, p_trimestre text, p_organizador text, p_fecha date, p_total integer, p_detalle jsonb, p_version integer default null::integer)
 returns void
 language plpgsql
 set search_path to 'public'
as $function$
begin
  update public.producciones
     set ramo          = p_ramo,
         trimestre     = p_trimestre,
         organizador   = p_organizador,
         ultima_fecha  = p_fecha,
         total_polizas = p_total
   where id = p_produccion_id
     and (p_version is null or version = p_version);

  if not found then
    if p_version is not null
       and exists (select 1 from public.producciones where id = p_produccion_id) then
      raise exception 'Otra persona modificó esta carga mientras la editabas. Recargá la página y volvé a aplicar tus cambios.';
    end if;

    raise exception 'No se encontró la carga, o no tenés permiso para editarla.';
  end if;

  delete from public.produccion_companias
   where produccion_id = p_produccion_id;

  insert into public.produccion_companias (produccion_id, compania, cantidad)
  select p_produccion_id, d->>'compania', (d->>'cantidad')::int
    from jsonb_array_elements(p_detalle) as d;
end;
$function$;

create or replace function public.eliminar_pas(p_pas_id bigint)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_rol text := public.mi_rol();
  v_ejecutivo text;
  v_tiene_produccion boolean;
begin
  select ejecutivo into v_ejecutivo from productores where id = p_pas_id;
  if v_ejecutivo is null then
    raise exception 'El PAS no existe';
  end if;

  select exists(select 1 from producciones where pas_id = p_pas_id) into v_tiene_produccion;

  if v_rol = 'admin' then
    null;
  elsif v_rol = 'editor' and public.tiene_dupla(v_ejecutivo) and not v_tiene_produccion then
    null;
  elsif v_rol = 'carga_pas' and public.tiene_dupla(v_ejecutivo) and not v_tiene_produccion then
    null;
  else
    raise exception 'No tenés permiso para eliminar este PAS';
  end if;

  delete from produccion_companias where produccion_id in (select id from producciones where pas_id = p_pas_id);
  delete from producciones where pas_id = p_pas_id;
  delete from productores where id = p_pas_id;
end;
$function$;

create or replace function public.eliminar_produccion(p_produccion_id bigint)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_ejecutivo text;
  v_rol text;
begin
  select ejecutivo into v_ejecutivo from producciones where id = p_produccion_id;
  if v_ejecutivo is null then
    raise exception 'La carga no existe.';
  end if;

  select rol into v_rol from usuarios where id = auth.uid();

  if v_rol = 'admin' then
  elsif v_rol = 'editor' and public.tiene_dupla(v_ejecutivo) then
  else
    raise exception 'No tenés permiso para eliminar esta carga.';
  end if;

  delete from produccion_companias where produccion_id = p_produccion_id;
  delete from producciones where id = p_produccion_id;
end;
$function$;

create or replace function public.eliminar_producciones_pas(p_pas_id bigint)
 returns integer
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_rol text;
  v_borradas integer;
begin
  select rol into v_rol from usuarios where id = auth.uid();

  if v_rol = 'admin' then
    delete from produccion_companias
      where produccion_id in (select id from producciones where pas_id = p_pas_id);
    delete from producciones where pas_id = p_pas_id;
    get diagnostics v_borradas = row_count;
  elsif v_rol = 'editor' then
    delete from produccion_companias
      where produccion_id in (
        select id from producciones
        where pas_id = p_pas_id and public.tiene_dupla(ejecutivo)
      );
    delete from producciones where pas_id = p_pas_id and public.tiene_dupla(ejecutivo);
    get diagnostics v_borradas = row_count;
  else
    raise exception 'No tenés permiso para eliminar cargas.';
  end if;

  return v_borradas;
end;
$function$;

-- El nombre se recorta y pasa a mayúsculas antes de guardarlo (y de chequear
-- si ya existe, ignorando mayúsculas/minúsculas), para que variantes como
-- "dupla_a" / "Dupla_A" / "dupla_a " no convivan como duplas distintas.
create or replace function public.crear_dupla_propia(p_nombre text)
 returns jsonb
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid uuid := auth.uid();
  v_rol text := mi_rol();
  v_rows int;
  v_nombre text := upper(trim(p_nombre));
begin
  if v_rol <> 'editor' then
    raise exception 'Solo un editor puede crear una dupla propia';
  end if;

  if v_nombre is null or v_nombre = '' then
    raise exception 'El nombre de la dupla no puede estar vacío';
  end if;

  if length(v_nombre) > 40 then
    raise exception 'El nombre de la dupla es demasiado largo (máximo 40 caracteres)';
  end if;

  if exists (select 1 from catalogos where tipo = 'ejecutivo' and lower(valor) = lower(v_nombre)) then
    raise exception 'Ya existe una dupla con ese nombre';
  end if;

  insert into catalogos (tipo, valor, activo) values ('ejecutivo', v_nombre, true);

  update usuarios
  set dupla_asignada = array_append(coalesce(dupla_asignada, '{}'::text[]), v_nombre)
  where id = v_uid;
  get diagnostics v_rows = row_count;

  return jsonb_build_object('uid', v_uid, 'rol', v_rol, 'filas_actualizadas', v_rows);
end;
$function$;

create or replace function public.eliminar_dupla_admin(p_nombre text)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  if mi_rol() <> 'admin' then
    raise exception 'Solo un admin puede eliminar cualquier dupla';
  end if;

  if exists (select 1 from productores where ejecutivo = p_nombre) then
    raise exception 'No se puede borrar: hay PAS cargados con esa dupla';
  end if;

  if exists (select 1 from metas where dupla = p_nombre) then
    raise exception 'No se puede borrar: hay metas cargadas con esa dupla';
  end if;

  update usuarios
  set dupla_asignada = array_remove(dupla_asignada, p_nombre)
  where p_nombre = any(coalesce(dupla_asignada, '{}'::text[]));

  delete from catalogos where tipo = 'ejecutivo' and valor = p_nombre;
end;
$function$;

create or replace function public.eliminar_dupla_propia(p_nombre text)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_uid uuid := auth.uid();
  v_rol text := mi_rol();
  v_mis_duplas text[] := coalesce((select dupla_asignada from usuarios where id = v_uid), '{}'::text[]);
begin
  if v_rol <> 'editor' then
    raise exception 'Solo un editor puede eliminar una dupla propia';
  end if;

  if not (p_nombre = any(v_mis_duplas)) then
    raise exception 'Esa dupla no está entre las tuyas';
  end if;

  if array_length(v_mis_duplas, 1) <= 1 then
    raise exception 'No podés quedarte sin ninguna dupla asignada';
  end if;

  if exists (select 1 from productores where ejecutivo = p_nombre) then
    raise exception 'No se puede borrar: hay PAS cargados con esa dupla';
  end if;

  if exists (select 1 from metas where dupla = p_nombre) then
    raise exception 'No se puede borrar: hay metas cargadas con esa dupla';
  end if;

  update usuarios
  set dupla_asignada = array_remove(dupla_asignada, p_nombre)
  where id = v_uid;

  if not exists (select 1 from usuarios where p_nombre = any(coalesce(dupla_asignada, '{}'::text[]))) then
    delete from catalogos where tipo = 'ejecutivo' and valor = p_nombre;
  end if;
end;
$function$;


-- ============================================================================
-- PASO 3 -- RLS: activarla y crear las políticas
-- ============================================================================

alter table public.productores enable row level security;
alter table public.producciones enable row level security;
alter table public.produccion_companias enable row level security;
alter table public.catalogos enable row level security;
alter table public.metas enable row level security;
alter table public.usuarios enable row level security;
alter table public.reportes enable row level security;
alter table public.audit_log enable row level security;

-- productores
create policy productores_select_todos on public.productores for select to authenticated
  using (exists (select 1 from usuarios u where u.id = auth.uid()));
create policy productores_admin_edita_todo on public.productores for all to authenticated
  using (mi_rol() = 'admin') with check (mi_rol() = 'admin');
create policy productores_editor_inserta_su_dupla on public.productores for insert to authenticated
  with check (mi_rol() = 'editor' and tiene_dupla(ejecutivo));
create policy productores_editor_edita_su_dupla on public.productores for update to authenticated
  using (mi_rol() = 'editor' and tiene_dupla(ejecutivo)) with check (mi_rol() = 'editor' and tiene_dupla(ejecutivo));
create policy carga_pas_inserta_su_dupla on public.productores for insert to authenticated
  with check (mi_rol() = 'carga_pas' and tiene_dupla(ejecutivo));
create policy carga_pas_edita_su_dupla on public.productores for update to authenticated
  using (mi_rol() = 'carga_pas' and tiene_dupla(ejecutivo));

-- producciones
create policy producciones_select_todos on public.producciones for select to authenticated
  using (exists (select 1 from usuarios u where u.id = auth.uid()));
create policy producciones_admin_edita_todo on public.producciones for all to authenticated
  using (mi_rol() = 'admin') with check (mi_rol() = 'admin');
create policy producciones_editor_gestiona_su_dupla on public.producciones for all to authenticated
  using (mi_rol() = 'editor' and exists (select 1 from productores p where p.id = producciones.pas_id and tiene_dupla(p.ejecutivo)))
  with check (mi_rol() = 'editor' and exists (select 1 from productores p where p.id = producciones.pas_id and tiene_dupla(p.ejecutivo)));

-- produccion_companias
create policy detalle_select_todos on public.produccion_companias for select to authenticated
  using (exists (select 1 from usuarios u where u.id = auth.uid()));
create policy detalle_admin_edita_todo on public.produccion_companias for all to authenticated
  using (mi_rol() = 'admin') with check (mi_rol() = 'admin');
create policy detalle_editor_gestiona_su_dupla on public.produccion_companias for all to authenticated
  using (mi_rol() = 'editor' and exists (select 1 from producciones pr join productores p on p.id = pr.pas_id where pr.id = produccion_companias.produccion_id and tiene_dupla(p.ejecutivo)))
  with check (mi_rol() = 'editor' and exists (select 1 from producciones pr join productores p on p.id = pr.pas_id where pr.id = produccion_companias.produccion_id and tiene_dupla(p.ejecutivo)));

-- catalogos
create policy catalogos_select_todos on public.catalogos for select to authenticated
  using (exists (select 1 from usuarios u where u.id = auth.uid()));
create policy catalogos_admin_edita on public.catalogos for all to authenticated
  using (mi_rol() = 'admin') with check (mi_rol() = 'admin');
create policy editor_inserta_dupla_catalogo on public.catalogos for insert to authenticated
  with check (mi_rol() = 'editor' and tipo = 'ejecutivo');

-- usuarios (dos generaciones de policies conviviendo: se combinan con OR,
-- funcionan, pero están anotadas como pendiente de consolidar)
create policy usuarios_select_propio_o_admin on public.usuarios for select to authenticated
  using (id = auth.uid() or mi_rol() = 'admin');
create policy usuarios_admin_todo on public.usuarios for all to authenticated
  using (mi_rol() = 'admin') with check (mi_rol() = 'admin');
create policy "admin lee todos los usuarios" on public.usuarios for select to authenticated
  using (es_admin());
create policy "admin actualiza usuarios" on public.usuarios for update to authenticated
  using (es_admin());
create policy "jefe lee todos los usuarios" on public.usuarios for select to authenticated
  using (es_jefe());

-- reportes
create policy "usuario ve sus propios reportes" on public.reportes for select to authenticated
  using (usuario_id = auth.uid());
create policy reportes_select_admin on public.reportes for select to authenticated
  using (mi_rol() = 'admin');
create policy reportes_insert_propio on public.reportes for insert to authenticated
  with check (usuario_id = auth.uid());
create policy reportes_update_admin on public.reportes for update to authenticated
  using (mi_rol() = 'admin') with check (mi_rol() = 'admin');
create policy reportes_delete_admin on public.reportes for delete to authenticated
  using (mi_rol() = 'admin');

-- metas
create policy metas_select_todos on public.metas for select to authenticated
  using (exists (select 1 from usuarios u where u.id = auth.uid()));
create policy metas_admin_edita_todo on public.metas for all to authenticated
  using (mi_rol() = any (array['admin','jefe'])) with check (mi_rol() = any (array['admin','jefe']));

-- audit_log
create policy audit_log_admin_lee on public.audit_log for select to authenticated
  using (mi_rol() = 'admin');
create policy audit_log_select_jefe on public.audit_log for select to authenticated
  using (es_jefe());


-- ============================================================================
-- PASO 4 -- Disparadores (triggers)
-- ============================================================================

create trigger trg_audit_productores after insert or delete or update on public.productores for each row execute function fn_audit_log();
create trigger trg_version_productores before update on public.productores for each row execute function fn_bump_version();
create trigger trg_audit_producciones after insert or delete or update on public.producciones for each row execute function fn_audit_log();
create trigger trg_version_producciones before update on public.producciones for each row execute function fn_bump_version();
create trigger trg_audit_produccion_companias after insert or delete or update on public.produccion_companias for each row execute function fn_audit_log();
create trigger trg_recalcular_total after insert or delete or update on public.produccion_companias for each row execute function fn_recalcular_total_produccion();
create trigger trg_reportes_autor before insert or update on public.reportes for each row execute function fn_reportes_autor();
create trigger trg_audit_usuarios after insert or delete or update on public.usuarios for each row execute function fn_audit_log();
create trigger trg_audit_catalogos after insert or delete or update on public.catalogos for each row execute function fn_audit_log();
create trigger trg_audit_metas after insert or delete or update on public.metas for each row execute function fn_audit_log();
create trigger trg_audit_reportes after insert or delete or update on public.reportes for each row execute function fn_audit_log();

-- Event trigger que activa RLS automáticamente en cualquier tabla nueva
drop event trigger if exists ensure_rls;
create event trigger ensure_rls on ddl_command_end execute function public.rls_auto_enable();


-- ============================================================================
-- PASO 5 -- Permisos: anon sin nada, authenticated acotado, funciones de
-- trigger sin EXECUTE para nadie (solo las dispara el motor internamente)
-- ============================================================================

alter default privileges in schema public revoke execute on functions from public;
alter default privileges in schema public revoke execute on functions from anon;
revoke execute on all functions in schema public from public, anon;
revoke all on all tables in schema public from public, anon;

grant select, insert, update, delete on
  public.productores, public.producciones, public.produccion_companias,
  public.catalogos, public.metas, public.usuarios, public.reportes, public.audit_log
to authenticated;

-- Helpers usados DENTRO de las policies: tienen que poder ejecutarlos
-- authenticated (y anon, para que una consulta sin sesión falle limpio en vez
-- de con "permission denied for function").
grant execute on function public.mi_rol() to authenticated, anon;
grant execute on function public.mi_dupla() to authenticated, anon;
grant execute on function public.tiene_dupla(text) to authenticated, anon;
grant execute on function public.es_admin() to authenticated, anon;
grant execute on function public.es_jefe() to authenticated, anon;

-- RPC que llama el frontend directo: EXECUTE explícito a authenticated. Su
-- protección es la validación de rol/dupla de adentro, no el permiso de
-- ejecución en sí.
grant execute on function public.crear_dupla_propia(text) to authenticated;
grant execute on function public.eliminar_dupla_propia(text) to authenticated;
grant execute on function public.eliminar_dupla_admin(text) to authenticated;
grant execute on function public.eliminar_pas(bigint) to authenticated;
grant execute on function public.eliminar_produccion(bigint) to authenticated;
grant execute on function public.eliminar_producciones_pas(bigint) to authenticated;
grant execute on function public.crear_produccion_completa(bigint,text,text,text,text,date,integer,jsonb) to authenticated;
grant execute on function public.guardar_produccion_completa(bigint,text,text,text,date,integer,jsonb,integer) to authenticated;

-- Funciones que SOLO dispara un trigger: nadie las llama por la API.
revoke execute on function public.fn_audit_log() from public, anon, authenticated;
revoke execute on function public.fn_bump_version() from authenticated;
revoke execute on function public.fn_recalcular_total_produccion() from authenticated;
revoke execute on function public.fn_reportes_autor() from authenticated;
revoke execute on function public.rls_auto_enable() from authenticated;

-- Realtime: publicado solo para metas y reportes, que son las únicas dos
-- tablas a las que se suscribe el frontend.
alter publication supabase_realtime add table public.metas, public.reportes;


-- ============================================================================
-- PASO 6 -- Datos de ejemplo: registros fabricados para pruebas
-- Ningún nombre, mail, teléfono o fecha de nacimiento de acá corresponde a
-- una persona real -- son generados con una fórmula determinística sobre
-- listas fijas de nombres/apellidos, no extraídos de ningún padrón.
-- ============================================================================

insert into public.catalogos (tipo, valor, activo) values
  ('ejecutivo','DEMO/ALFA',true),
  ('ejecutivo','DEMO/BETA',true),
  ('ejecutivo','DEMO/GAMMA',true),
  ('ejecutivo','DEMO/DELTA',true),
  ('ejecutivo','DEMO/EPSILON',true),
  ('compania','Compañía Demo A',true),
  ('compania','Compañía Demo B',true),
  ('compania','Compañía Demo C',true),
  ('organizacion','Organización Demo Norte',true),
  ('organizacion','Organización Demo Sur',true),
  ('organizacion','Organización Demo Litoral',true),
  ('organizacion','Organización Demo Cuyo',true),
  ('zona','Norte',true),
  ('zona','Sur',true),
  ('zona','Centro',true),
  ('ramo','AUTOMOTOR',true),
  ('ramo','VIDA',true),
  ('ramo','ROBO',true),
  ('ramo','ACC. PERS.',true),
  ('ramo','COMBINADO FAM.',true),
  ('estado','Activo',true),
  ('estado','Inactivo',true),
  ('trimestre','T1 2026',true),
  ('trimestre','T2 2026',true),
  ('trimestre','T3 2026',true),
  ('trimestre','T4 2026',true);

with nombres as (
  select array['Agustín','Alejandra','Andrés','Ana','Bruno','Beatriz','Carlos','Carla','Damián','Daniela',
    'Emiliano','Elena','Facundo','Florencia','Gastón','Gabriela','Hernán','Inés','Ignacio','Irene',
    'Joaquín','Julieta','Leandro','Lucía','Martín','Mariana','Nicolás','Noelia','Octavio','Olivia',
    'Pablo','Paula','Ramiro','Rocío','Santiago','Sofía','Tomás','Valeria','Víctor','Verónica']::text[] as arr
),
apellidos as (
  select array['Aguirre','Álvarez','Benítez','Bianchi','Cabrera','Carrizo','Domínguez','Duarte','Escobar','Esquivel',
    'Ferreyra','Figueroa','Gallardo','Godoy','Herrera','Ibarra','Juárez','Ledesma','Luna','Maldonado',
    'Medina','Miranda','Navarro','Ocampo','Olivera','Paredes','Peralta','Quiroga','Ramírez','Rivas',
    'Sarmiento','Sosa','Tejada','Toledo','Urquiza','Valdez','Vega','Villalba','Zabala','Zárate']::text[] as arr
),
duplas as (select array['DEMO/ALFA','DEMO/BETA','DEMO/GAMMA','DEMO/DELTA','DEMO/EPSILON']::text[] as arr),
orgs as (select array['Organización Demo Norte','Organización Demo Sur','Organización Demo Litoral','Organización Demo Cuyo']::text[] as arr)
insert into public.productores
  (pas_nombre, organizacion, vinculante, ejecutivo, telefono, mail, fecha_nacimiento, companias_opera, cantidad_polizas_vigentes, estado, zona, localidad_prov)
select
  apellidos.arr[1 + (i*7) % 40] || ' ' || nombres.arr[1 + (i*13) % 40],
  orgs.arr[1 + i % 4],
  case when i % 2 = 0 then 'SI' else 'NO' end,
  duplas.arr[1 + i % 5],
  '11' || lpad((10000000 + i)::text, 8, '0'),
  'demo.pas' || i || '@ejemplo-abgestion.com',
  date '1975-01-01' + ((i * 137) % 16000) * interval '1 day',
  'Compañía Demo A, Compañía Demo B',
  i % 15,
  case when i % 4 = 0 then 'Inactivo' else 'Activo' end,
  (array['Norte','Sur','Centro'])[1 + i % 3],
  'Ciudad Demo ' || (i % 6)
from generate_series(1,50) as i, nombres, apellidos, duplas, orgs;

insert into public.producciones (pas_id, ramo, trimestre, ejecutivo, organizador, ultima_fecha, total_polizas)
select p.id,
  (array['AUTOMOTOR','VIDA','ROBO','ACC. PERS.','COMBINADO FAM.'])[1 + (p.id % 5)::int],
  'T' || (1 + (p.id % 4)) || ' 2026',
  p.ejecutivo,
  'Organizador Demo',
  current_date - (p.id % 90)::int,
  0
from public.productores p
where p.id % 2 = 0;

insert into public.produccion_companias (produccion_id, compania, cantidad)
select pr.id, 'Compañía Demo ' || chr(65 + (pr.id % 3)::int), 1 + (pr.id % 10)
from public.producciones pr;

insert into public.metas (dupla, trimestre, objetivo_polizas) values ('DEMO/ALFA','T1 2026', 50);


-- ============================================================================
-- PASO 7 -- Verificación (solo lectura)
-- ============================================================================

select count(*) as total_productores_de_prueba from public.productores;
select count(*) as total_producciones_de_prueba from public.producciones;
select relname, relrowsecurity from pg_class where relnamespace = 'public'::regnamespace and relkind = 'r';
select count(*) as total_policies
  from pg_policy p
  join pg_class c on c.oid = p.polrelid
  join pg_namespace n on n.oid = c.relnamespace
 where n.nspname = 'public';
